// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/momoyo-droid/capim/api/internal/model"
	"github.com/momoyo-droid/capim/api/internal/service"
	"sync"
)

// Ensure, that SellerRepositoryMock does implement service.SellerRepository.
// If this is not the case, regenerate this file with moq.
var _ service.SellerRepository = &SellerRepositoryMock{}

// SellerRepositoryMock is a mock implementation of service.SellerRepository.
//
//	func TestSomethingThatUsesSellerRepository(t *testing.T) {
//
//		// make and configure a mocked service.SellerRepository
//		mockedSellerRepository := &SellerRepositoryMock{
//			CheckSellerByDocumentFunc: func(ctx context.Context, document string) (model.Seller, error) {
//				panic("mock out the CheckSellerByDocument method")
//			},
//			CreateSellerFunc: func(ctx context.Context, seller model.Seller) error {
//				panic("mock out the CreateSeller method")
//			},
//			DeleteSellerByIDFunc: func(ctx context.Context, sellerID uint64) error {
//				panic("mock out the DeleteSellerByID method")
//			},
//			GetAllSellersFunc: func(ctx context.Context) ([]model.Seller, error) {
//				panic("mock out the GetAllSellers method")
//			},
//			GetSellerByIDFunc: func(ctx context.Context, sellerID uint64) (model.Seller, error) {
//				panic("mock out the GetSellerByID method")
//			},
//			UpdateOwnerByIDFunc: func(ctx context.Context, ownerID uint64, updatedOwner model.Owner) error {
//				panic("mock out the UpdateOwnerByID method")
//			},
//			UpdateSellerByIDFunc: func(ctx context.Context, sellerID uint64, updatedSeller model.Seller) error {
//				panic("mock out the UpdateSellerByID method")
//			},
//		}
//
//		// use mockedSellerRepository in code that requires service.SellerRepository
//		// and then make assertions.
//
//	}
type SellerRepositoryMock struct {
	// CheckSellerByDocumentFunc mocks the CheckSellerByDocument method.
	CheckSellerByDocumentFunc func(ctx context.Context, document string) (model.Seller, error)

	// CreateSellerFunc mocks the CreateSeller method.
	CreateSellerFunc func(ctx context.Context, seller model.Seller) error

	// DeleteSellerByIDFunc mocks the DeleteSellerByID method.
	DeleteSellerByIDFunc func(ctx context.Context, sellerID uint64) error

	// GetAllSellersFunc mocks the GetAllSellers method.
	GetAllSellersFunc func(ctx context.Context) ([]model.Seller, error)

	// GetSellerByIDFunc mocks the GetSellerByID method.
	GetSellerByIDFunc func(ctx context.Context, sellerID uint64) (model.Seller, error)

	// UpdateOwnerByIDFunc mocks the UpdateOwnerByID method.
	UpdateOwnerByIDFunc func(ctx context.Context, ownerID uint64, updatedOwner model.Owner) error

	// UpdateSellerByIDFunc mocks the UpdateSellerByID method.
	UpdateSellerByIDFunc func(ctx context.Context, sellerID uint64, updatedSeller model.Seller) error

	// calls tracks calls to the methods.
	calls struct {
		// CheckSellerByDocument holds details about calls to the CheckSellerByDocument method.
		CheckSellerByDocument []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Document is the document argument value.
			Document string
		}
		// CreateSeller holds details about calls to the CreateSeller method.
		CreateSeller []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Seller is the seller argument value.
			Seller model.Seller
		}
		// DeleteSellerByID holds details about calls to the DeleteSellerByID method.
		DeleteSellerByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SellerID is the sellerID argument value.
			SellerID uint64
		}
		// GetAllSellers holds details about calls to the GetAllSellers method.
		GetAllSellers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetSellerByID holds details about calls to the GetSellerByID method.
		GetSellerByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SellerID is the sellerID argument value.
			SellerID uint64
		}
		// UpdateOwnerByID holds details about calls to the UpdateOwnerByID method.
		UpdateOwnerByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OwnerID is the ownerID argument value.
			OwnerID uint64
			// UpdatedOwner is the updatedOwner argument value.
			UpdatedOwner model.Owner
		}
		// UpdateSellerByID holds details about calls to the UpdateSellerByID method.
		UpdateSellerByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SellerID is the sellerID argument value.
			SellerID uint64
			// UpdatedSeller is the updatedSeller argument value.
			UpdatedSeller model.Seller
		}
	}
	lockCheckSellerByDocument sync.RWMutex
	lockCreateSeller          sync.RWMutex
	lockDeleteSellerByID      sync.RWMutex
	lockGetAllSellers         sync.RWMutex
	lockGetSellerByID         sync.RWMutex
	lockUpdateOwnerByID       sync.RWMutex
	lockUpdateSellerByID      sync.RWMutex
}

// CheckSellerByDocument calls CheckSellerByDocumentFunc.
func (mock *SellerRepositoryMock) CheckSellerByDocument(ctx context.Context, document string) (model.Seller, error) {
	if mock.CheckSellerByDocumentFunc == nil {
		panic("SellerRepositoryMock.CheckSellerByDocumentFunc: method is nil but SellerRepository.CheckSellerByDocument was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Document string
	}{
		Ctx:      ctx,
		Document: document,
	}
	mock.lockCheckSellerByDocument.Lock()
	mock.calls.CheckSellerByDocument = append(mock.calls.CheckSellerByDocument, callInfo)
	mock.lockCheckSellerByDocument.Unlock()
	return mock.CheckSellerByDocumentFunc(ctx, document)
}

// CheckSellerByDocumentCalls gets all the calls that were made to CheckSellerByDocument.
// Check the length with:
//
//	len(mockedSellerRepository.CheckSellerByDocumentCalls())
func (mock *SellerRepositoryMock) CheckSellerByDocumentCalls() []struct {
	Ctx      context.Context
	Document string
} {
	var calls []struct {
		Ctx      context.Context
		Document string
	}
	mock.lockCheckSellerByDocument.RLock()
	calls = mock.calls.CheckSellerByDocument
	mock.lockCheckSellerByDocument.RUnlock()
	return calls
}

// CreateSeller calls CreateSellerFunc.
func (mock *SellerRepositoryMock) CreateSeller(ctx context.Context, seller model.Seller) error {
	if mock.CreateSellerFunc == nil {
		panic("SellerRepositoryMock.CreateSellerFunc: method is nil but SellerRepository.CreateSeller was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Seller model.Seller
	}{
		Ctx:    ctx,
		Seller: seller,
	}
	mock.lockCreateSeller.Lock()
	mock.calls.CreateSeller = append(mock.calls.CreateSeller, callInfo)
	mock.lockCreateSeller.Unlock()
	return mock.CreateSellerFunc(ctx, seller)
}

// CreateSellerCalls gets all the calls that were made to CreateSeller.
// Check the length with:
//
//	len(mockedSellerRepository.CreateSellerCalls())
func (mock *SellerRepositoryMock) CreateSellerCalls() []struct {
	Ctx    context.Context
	Seller model.Seller
} {
	var calls []struct {
		Ctx    context.Context
		Seller model.Seller
	}
	mock.lockCreateSeller.RLock()
	calls = mock.calls.CreateSeller
	mock.lockCreateSeller.RUnlock()
	return calls
}

// DeleteSellerByID calls DeleteSellerByIDFunc.
func (mock *SellerRepositoryMock) DeleteSellerByID(ctx context.Context, sellerID uint64) error {
	if mock.DeleteSellerByIDFunc == nil {
		panic("SellerRepositoryMock.DeleteSellerByIDFunc: method is nil but SellerRepository.DeleteSellerByID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SellerID uint64
	}{
		Ctx:      ctx,
		SellerID: sellerID,
	}
	mock.lockDeleteSellerByID.Lock()
	mock.calls.DeleteSellerByID = append(mock.calls.DeleteSellerByID, callInfo)
	mock.lockDeleteSellerByID.Unlock()
	return mock.DeleteSellerByIDFunc(ctx, sellerID)
}

// DeleteSellerByIDCalls gets all the calls that were made to DeleteSellerByID.
// Check the length with:
//
//	len(mockedSellerRepository.DeleteSellerByIDCalls())
func (mock *SellerRepositoryMock) DeleteSellerByIDCalls() []struct {
	Ctx      context.Context
	SellerID uint64
} {
	var calls []struct {
		Ctx      context.Context
		SellerID uint64
	}
	mock.lockDeleteSellerByID.RLock()
	calls = mock.calls.DeleteSellerByID
	mock.lockDeleteSellerByID.RUnlock()
	return calls
}

// GetAllSellers calls GetAllSellersFunc.
func (mock *SellerRepositoryMock) GetAllSellers(ctx context.Context) ([]model.Seller, error) {
	if mock.GetAllSellersFunc == nil {
		panic("SellerRepositoryMock.GetAllSellersFunc: method is nil but SellerRepository.GetAllSellers was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAllSellers.Lock()
	mock.calls.GetAllSellers = append(mock.calls.GetAllSellers, callInfo)
	mock.lockGetAllSellers.Unlock()
	return mock.GetAllSellersFunc(ctx)
}

// GetAllSellersCalls gets all the calls that were made to GetAllSellers.
// Check the length with:
//
//	len(mockedSellerRepository.GetAllSellersCalls())
func (mock *SellerRepositoryMock) GetAllSellersCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAllSellers.RLock()
	calls = mock.calls.GetAllSellers
	mock.lockGetAllSellers.RUnlock()
	return calls
}

// GetSellerByID calls GetSellerByIDFunc.
func (mock *SellerRepositoryMock) GetSellerByID(ctx context.Context, sellerID uint64) (model.Seller, error) {
	if mock.GetSellerByIDFunc == nil {
		panic("SellerRepositoryMock.GetSellerByIDFunc: method is nil but SellerRepository.GetSellerByID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SellerID uint64
	}{
		Ctx:      ctx,
		SellerID: sellerID,
	}
	mock.lockGetSellerByID.Lock()
	mock.calls.GetSellerByID = append(mock.calls.GetSellerByID, callInfo)
	mock.lockGetSellerByID.Unlock()
	return mock.GetSellerByIDFunc(ctx, sellerID)
}

// GetSellerByIDCalls gets all the calls that were made to GetSellerByID.
// Check the length with:
//
//	len(mockedSellerRepository.GetSellerByIDCalls())
func (mock *SellerRepositoryMock) GetSellerByIDCalls() []struct {
	Ctx      context.Context
	SellerID uint64
} {
	var calls []struct {
		Ctx      context.Context
		SellerID uint64
	}
	mock.lockGetSellerByID.RLock()
	calls = mock.calls.GetSellerByID
	mock.lockGetSellerByID.RUnlock()
	return calls
}

// UpdateOwnerByID calls UpdateOwnerByIDFunc.
func (mock *SellerRepositoryMock) UpdateOwnerByID(ctx context.Context, ownerID uint64, updatedOwner model.Owner) error {
	if mock.UpdateOwnerByIDFunc == nil {
		panic("SellerRepositoryMock.UpdateOwnerByIDFunc: method is nil but SellerRepository.UpdateOwnerByID was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		OwnerID      uint64
		UpdatedOwner model.Owner
	}{
		Ctx:          ctx,
		OwnerID:      ownerID,
		UpdatedOwner: updatedOwner,
	}
	mock.lockUpdateOwnerByID.Lock()
	mock.calls.UpdateOwnerByID = append(mock.calls.UpdateOwnerByID, callInfo)
	mock.lockUpdateOwnerByID.Unlock()
	return mock.UpdateOwnerByIDFunc(ctx, ownerID, updatedOwner)
}

// UpdateOwnerByIDCalls gets all the calls that were made to UpdateOwnerByID.
// Check the length with:
//
//	len(mockedSellerRepository.UpdateOwnerByIDCalls())
func (mock *SellerRepositoryMock) UpdateOwnerByIDCalls() []struct {
	Ctx          context.Context
	OwnerID      uint64
	UpdatedOwner model.Owner
} {
	var calls []struct {
		Ctx          context.Context
		OwnerID      uint64
		UpdatedOwner model.Owner
	}
	mock.lockUpdateOwnerByID.RLock()
	calls = mock.calls.UpdateOwnerByID
	mock.lockUpdateOwnerByID.RUnlock()
	return calls
}

// UpdateSellerByID calls UpdateSellerByIDFunc.
func (mock *SellerRepositoryMock) UpdateSellerByID(ctx context.Context, sellerID uint64, updatedSeller model.Seller) error {
	if mock.UpdateSellerByIDFunc == nil {
		panic("SellerRepositoryMock.UpdateSellerByIDFunc: method is nil but SellerRepository.UpdateSellerByID was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		SellerID      uint64
		UpdatedSeller model.Seller
	}{
		Ctx:           ctx,
		SellerID:      sellerID,
		UpdatedSeller: updatedSeller,
	}
	mock.lockUpdateSellerByID.Lock()
	mock.calls.UpdateSellerByID = append(mock.calls.UpdateSellerByID, callInfo)
	mock.lockUpdateSellerByID.Unlock()
	return mock.UpdateSellerByIDFunc(ctx, sellerID, updatedSeller)
}

// UpdateSellerByIDCalls gets all the calls that were made to UpdateSellerByID.
// Check the length with:
//
//	len(mockedSellerRepository.UpdateSellerByIDCalls())
func (mock *SellerRepositoryMock) UpdateSellerByIDCalls() []struct {
	Ctx           context.Context
	SellerID      uint64
	UpdatedSeller model.Seller
} {
	var calls []struct {
		Ctx           context.Context
		SellerID      uint64
		UpdatedSeller model.Seller
	}
	mock.lockUpdateSellerByID.RLock()
	calls = mock.calls.UpdateSellerByID
	mock.lockUpdateSellerByID.RUnlock()
	return calls
}
